import React from "react";

export default function Terms() {
  return (
    <main className="relative pt-24 pb-16 min-h-screen px-6 max-w-4xl mx-auto">
      <div className="glass-panel bg-surface-variant/40 border border-outline-variant/15 rounded-xl p-8 md:p-12">
        <h1 className="font-headline text-4xl font-bold mb-6 text-on-surface">Terms & Conditions</h1>
        <p className="text-on-surface-variant italic mb-8">Last Updated: October 2024</p>
        
        <div className="space-y-6 text-on-surface-variant leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-on-surface mb-3">1. AI Generated Content</h2>
            <p>CaptionCraft utilizes Artificial Intelligence to generate content. While we strive for high quality, we do not guarantee the accuracy, completeness, or suitability of generated captions. You are responsible for reviewing content before publishing on your social media platforms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-on-surface mb-3">2. User Accounts</h2>
            <p>When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-on-surface mb-3">3. Acceptable Use</h2>
            <p>You agree not to use CaptionCraft to generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or racially/ethnically objectionable.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-on-surface mb-3">4. Intellectual Property</h2>
            <p>The service and its original content (excluding content provided by users or generated by AI) are and will remain the exclusive property of CaptionCraft and its licensors.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-on-surface mb-3">5. Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at <a href="mailto:nexasolutionspvtltd@gmail.com" className="text-primary hover:underline font-bold">nexasolutionspvtltd@gmail.com</a>.</p>
          </section>
        </div>
      </div>
    </main>
  );
}
